site_name: AttraxBet Docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
  logo: Alogo.png        # must exist in docs/
  favicon: Alogo.png     # optional; same image is fine

extra:
  homepage: https://attrax.bet/

extra_css:
  - overrides/extra.css
extra_javascript:
  - overrides/extra.js

nav:
  - Home: index.md
  - Fairness: fairness.md
  - Games: games.md
  - AttraXPoints: attraxpoints.md
  - Contact: contact.md

plugins: []

